language: cpp

cache:
  apt: true

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - os: linux
      compiler: clang
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 CXX_COMPILER=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-6
          sources: *sources

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
  - ${CXX} --version
  - mkdir build
  - cd build
  - cmake .. && make
